Models/Doctor.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ClinicManagement.Models
{
    public class Doctor
    {
        [Key]
        public int ID { get; set; }

        [Display(Name ="Tên")]
        [Required(ErrorMessage ="phải nhập {0}")]
        [StringLength(20,ErrorMessage ="{0} phải từ {2} đến {1} ký tự",MinimumLength =1)]
        public string FName { get; set; }

        [Display(Name ="Họ")]
        [Required(ErrorMessage ="phải nhập {0}")]
        [StringLength(20,ErrorMessage ="{0} phải từ {2} đến {1} ký tự",MinimumLength =1)]
        public string LName { get; set; }

        [Display(Name ="Tuổi")]
        public int? Age { get; set; }

            [Display(Name ="Điện thoại")]
        // [Required(ErrorMessage ="phải nhập {0}")]
        [Phone(ErrorMessage ="Điện thoại không hợp lệ")]
        public string Phone { get; set; }
        [Display(Name ="Email")]
        // [Required(ErrorMessage ="phải nhập {0}")]
        // [StringLength(60,ErrorMessage ="{0} phải từ {2} đến {1} ký tự",MinimumLength =3)]
        [EmailAddress(ErrorMessage ="Địa chỉ Email không hợp lệ")]
        public string Email { get; set; }

        [Display(Name ="Ngày Đăng ký")]
        [DataType(DataType.Date)]
        public DateTime Registed_Date { get; set; }=DateTime.Now;
       
        [Display(Name ="Giới tính")]

        public int? GenderID { get; set; }
        [ForeignKey("GenderID")]
        public virtual Gender gender{set;get;}

        [Display(Name ="Nhóm máu")]
         public int? BloodGroupID { get; set; }
        [ForeignKey("BloodGroupID")]
        public virtual BloodGroup boolGroup{set;get;}

        public int? AddressID { get; set; }
        [ForeignKey("AddressID")]
        public virtual Address address{set;get;}


        public bool Doctor_Status{get;set;}

        public string ImatePath{get;set;}

        [Display(Name ="Tên bác sĩ")]

        [NotMapped]
        public string FullName 
        {
            get { return LName + " " +FName ;}
        }

    }
}

Controllers/DoctorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ClinicManagement.Models;
using ClinicManagement.Interfaces;
using ClinicManagement.Tools;

namespace ClinicManagement.Controllers
{
    [Route("{Controller}/{action}/{id?}")]
    public class DoctorController : Controller
    {
         public class doctordata{
        public Doctor datadoctor{get;set;}
        public string Street{get;set;}
        public string city{get;set;}
        public string province{get;set;}
        public string Post_Code{get;set;}
       }
        private readonly IDoctor _doctorRepo;
        private readonly IAddress _address;

        public DoctorController(IDoctor doctor,IAddress address)
        {
            //_context = context;
            _doctorRepo=doctor;
            _address=address;
        }
       

        // GET: Doctor
        public IActionResult Index(string sortExpression="", string SearchText = "",int pg=1,int pageSize=5)
        {
            SortModel sortModel=new SortModel();
            sortModel.AddColumn("fname");
            sortModel.AddColumn("lname");
            sortModel.AddColumn("age");
            sortModel.ApplySort(sortExpression);
            ViewData["sortModel"] = sortModel;


            ViewBag.SearchText=SearchText;
            PaginatedList<Doctor> doctors=_doctorRepo.GetItems(sortModel.SortedProperty,sortModel.SortedOrder,SearchText,pg,pageSize);

            var pager=new PagerModel(doctors.TotalRecords,pg,pageSize);
            pager.SortExpression=sortExpression;
            this.ViewBag.Pager=pager;

            TempData["CurrentPage"]=pg;
            return View(doctors);
            
        }

        // GET: Doctor/Details/5
        public IActionResult Details(int id)
        {
            
            var doctor= _doctorRepo.GetDoctor(id);
         
            if (doctor == null)
            {
                return NotFound();
            }

            return View(doctor);
        }

        // GET: Doctor/Create
        public IActionResult Create()
        {
            ViewData["GenderID"] = new SelectList(_doctorRepo.GetGenderList(), "ID", "Name");
            ViewData["BloodGroupID"] = new SelectList(_doctorRepo.GetBloodGroupList(), "ID", "Name");

            var doctorAddress=new doctordata{datadoctor=new Doctor()};

            return View(doctorAddress);
        }

        // POST: Doctor/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create( [Bind("datadoctor,Street,city,province,Post_Code")]doctordata doctor)
        {
            if (ModelState.IsValid)
            {
                // _context.Add(doctor);
                // await _context.SaveChangesAsync();
                // return RedirectToAction(nameof(Index));
                if (doctor.datadoctor.GenderID == -1) doctor.datadoctor.GenderID = null;
                    if (doctor.datadoctor.BloodGroupID == -1) doctor.datadoctor.BloodGroupID = null;
                    //if (patient.address?.Street == string.Empty&&patient.address?.City==string.Empty) patient.AddressID = null;
                    //Console.WriteLine($"ten duong {patientAddress.Street}" +"city "+ $"{patientAddress.city}");
                     if(!string.IsNullOrEmpty(doctor.Street)||!string.IsNullOrEmpty(doctor.city))
                    {
                        Address addr=new Address(){
                            Street=doctor.Street,
                            City=doctor.city,
                            Province=doctor.province,
                            Post_Code=doctor.Post_Code
                        };
                        addr= _address.Create(addr);
                        doctor.datadoctor.AddressID=addr.ID;
                    }
                    else
                    {
                        doctor.datadoctor.address=null;
                        doctor.datadoctor.AddressID=null;
                    }
                // _context.Add(patient);
                // await _context.SaveChangesAsync();
                // return RedirectToAction(nameof(Index));
                doctor.datadoctor.Registed_Date=DateTime.Now;
                doctor.datadoctor = _doctorRepo.Create(doctor.datadoctor);
                return RedirectToAction(nameof(Index));

            }
             ViewData["GenderID"] = new SelectList(_doctorRepo.GetGenderList(), "ID", "Name");
            ViewData["BloodGroupID"] = new SelectList(_doctorRepo.GetBloodGroupList(), "ID", "Name");
            return View(doctor);
        }

        // GET: Doctor/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doctor = _doctorRepo.GetDoctor(id);
            if (doctor == null)
            {
                return NotFound();
            }           
            //doctor.address=_doctorRepo.GetAddress(doctor.AddressID);
            ViewData["GenderID"] = new SelectList(_doctorRepo.GetGenderList(), "ID", "Name");
            ViewData["BloodGroupID"] = new SelectList(_doctorRepo.GetBloodGroupList(), "ID", "Name");
            var data=new doctordata(){datadoctor=doctor,
                                                    Street=doctor.address?.Street,
                                                    city=doctor.address?.City,
                                                    province=doctor.address?.Province,
                                                    Post_Code=doctor.address?.Post_Code};
            return View(data);
        }

        // POST: Doctor/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int? id, [Bind("datadoctor,Street,city,province,Post_Code")]doctordata doctor)
        {
            if (id ==null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //patientAddress.Patient=_patientRepo.GetPatient(id);
                    if(doctor.datadoctor==null)
                    {
                        return NotFound();
                    }
                     doctor.datadoctor.Registed_Date=DateTime.Now;
                    if (doctor.datadoctor.GenderID == -1) doctor.datadoctor.GenderID = null;
                    if (doctor.datadoctor.BloodGroupID == -1) doctor.datadoctor.BloodGroupID = null;

                    if(doctor.datadoctor.AddressID==null && (!string.IsNullOrEmpty(doctor.Street)||!string.IsNullOrEmpty(doctor.city)))
                    {
                        Address addr = new Address(){Street=doctor.Street,
                                                        City=doctor.city,
                                                        Province=doctor.province,
                                                        Post_Code=doctor.Post_Code
                                                        };
                        addr= _address.Create(addr);
                        doctor.datadoctor.AddressID=addr.ID;
                    }else if(doctor.datadoctor.AddressID!=null)
                    {
                        Console.WriteLine($"Edit address {doctor.Street}");
                        Address addr= _address.GetAddress(doctor.datadoctor.AddressID);
                        addr.Street=doctor.Street;
                        addr.City=doctor.city;
                        addr.Province=doctor.province;
                        addr.Post_Code=doctor.Post_Code;
                        _address.Edit(addr);
                    }              


                 
                     _doctorRepo.Edit(doctor.datadoctor);

                }
                catch (DbUpdateConcurrencyException)
                {
                    
                }
                return RedirectToAction(nameof(Index));
            }
             ViewData["GenderID"] = new SelectList(_doctorRepo.GetGenderList(), "ID", "Name");
            ViewData["BloodGroupID"] = new SelectList(_doctorRepo.GetBloodGroupList(), "ID", "Name");
            return View(doctor);
        }

        // GET: Doctor/Delete/5
        public IActionResult Delete(int id)
        {       

            var doctor = _doctorRepo.GetDoctor(id);
            if (doctor == null)
            {
                return NotFound();
            }

            return View(doctor);
        }

        // POST: Doctor/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var doctor = _doctorRepo.GetDoctor(id);
            if(doctor==null)
                return NotFound();
            Address address=doctor.address;
            doctor=_doctorRepo.Delete(doctor);
            if(address!=null)
                _address.Delete(address);
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Doctor/Create.cshtml
@using ClinicManagement.Menu
@inject AdminSidebarService _AdminSidebarService
@* @model ClinicManagement.Models.Patient *@
@model ClinicManagement.Controllers.DoctorController.doctordata

@{
    ViewData["Title"] = "Thêm mới bác sĩ";

}
<partial name="_StatusMessage" />


<div class="card-header bg-success text-uppercase text-white text-center mb-2 pb-4" style="height: 25px;">
    <h6>@ViewData["Title"]</h6>
</div>

<form asp-action="Create">
    <div class="row col-12">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group col-2">
                <label asp-for="@Model.datadoctor.FName" class="control-label"></label>                
            </div>
            <div class="form-group col-3">
                <input asp-for="@Model.datadoctor.FName" class="form-control" />
                <span asp-validation-for="@Model.datadoctor.FName" class="text-danger"></span>
            </div>

            <div class="form-group col-2"></div>

             <div class="form-group col-2">
                <label asp-for="@Model.datadoctor.LName" class="control-label"></label>                
            </div>
            <div class="form-group col-3">
                <input asp-for="@Model.datadoctor.LName" class="form-control" />
                <span asp-validation-for="@Model.datadoctor.LName" class="text-danger"></span>
            </div>

            <div class="form-group col-2">
                <label asp-for="@Model.datadoctor.Age" class="control-label"></label>                
            </div>
            <div class="form-group col-3">
                <input type="number" asp-for="@Model.datadoctor.Age" class="form-control" />
                <span asp-validation-for="@Model.datadoctor.Age" class="text-danger"></span>
            </div>

            <div class="form-group col-2"></div>

             <div class="form-group col-2">
                <label asp-for="@Model.datadoctor.Phone" class="control-label"></label>                
            </div>
            <div class="form-group col-3">
                <input asp-for="@Model.datadoctor.Phone" class="form-control" />
                <span asp-validation-for="@Model.datadoctor.Phone" class="text-danger"></span>
            </div>

             <div class="form-group col-2">
                <label asp-for="@Model.datadoctor.Email" class="control-label"></label>                
            </div>
            <div class="form-group col-3">
                <input asp-for="@Model.datadoctor.Email" class="form-control" />
                <span asp-validation-for="@Model.datadoctor.Email" class="text-danger"></span>
            </div>

            <div class="form-group col-2"></div>


            <div class="form-group col-2">
                <label asp-for="@Model.datadoctor.GenderID" class="control-label"></label>
            </div>
             <div class="form-group col-3">
                <select asp-for="@Model.datadoctor.GenderID" class ="form-control" asp-items="ViewBag.GenderID"></select>
            </div>
            <div class="form-group col-2">
                <label asp-for="@Model.datadoctor.BloodGroupID" class="control-label"></label>
            </div>
            <div class="form-group col-3">
                <select asp-for="@Model.datadoctor.BloodGroupID" class ="form-control" asp-items="ViewBag.BloodGroupID"></select>
            </div>
            <div class="form-group col-7"></div>


<div class="card-header bg-warning text-uppercase text-white text-center mb-2 pb-4 col-12" style="height: 25px;">
    <h7>Thông tin địa chỉ bác sĩ</h7>
</div>

            <div class="form-group col-2">
                <label asp-for="@Model.Street" value="Tên đường" class="control-label"></label>                
            </div>
            <div class="form-group col-3">
                <input id="streetid" name="Street" asp-for="@Model.Street" class="form-control" />
                <span asp-validation-for="@Model.Street" class="text-danger"></span>
            </div>

            <div class="form-group col-2"></div>

             <div class="form-group col-2">
                <label asp-for="@Model.city" value="Thành phố" class="control-label"></label>                
            </div>
            <div class="form-group col-3">
                <input id="cityid"  name="City" asp-for="@Model.city" class="form-control" />
                <span asp-validation-for="@Model.city" class="text-danger"></span>
            </div>
            <div class="form-group col-2">
                <label asp-for="@Model.province" value="Tỉnh Thành" class="control-label"></label>                
            </div>
            <div class="form-group col-3">
                <input id="provinceid" asp-for="@Model.province" class="form-control" />
                <span asp-validation-for="@Model.province" class="text-danger"></span>
            </div>

            <div class="form-group col-2"></div>

             <div class="form-group col-2">
                <label asp-for="@Model.Post_Code" value="Mã bưu điện" class="control-label"></label>                
            </div>
            <div class="form-group col-3">
                <input id="postcodeid" asp-for="@Model.Post_Code"  class="form-control" />
                <span asp-validation-for="@Model.Post_Code" class="text-danger"></span>
            </div>

<div class="col-12">

</div>            
           
             <div class="form-group btn-group col-12">
                <div class="col-1"></div>
                <div class="col-5">
                <input type="submit" value="Thêm mới" class="btn btn-primary btn-block" />
                </div>
                <div class="col-5">
                 <a class="btn btn-secondary btn-block" asp-action="index"
                   asp-route-pg="@TempData.Peek("CurrentPage")">danh sách bác sĩ</a>
                </div>
            </div>
           
    </div>
</form>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}

@section Sidebar
{
    @Html.Raw(_AdminSidebarService.renderHtml())
}

Views/Doctor/Delete.cshtml
@using ClinicManagement.Menu
@inject AdminSidebarService _AdminSidebarService
@model ClinicManagement.Models.Doctor

@{
    ViewData["Title"] = "Xóa bác sĩ";
}

<h3>Bạn muốn xóa bác sĩ này?</h3>
<div>
  
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Registed_Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Registed_Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.gender.Name)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.boolGroup)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.boolGroup.Name)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.address.ID)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Danh sách bác sĩ</a>
    </form>
</div>

@section Sidebar
{
    @Html.Raw(_AdminSidebarService.renderHtml())
}

Views/Doctor/Details.cshtml
@using ClinicManagement.Menu
@inject AdminSidebarService _AdminSidebarService
@model ClinicManagement.Models.Doctor

@{
    ViewData["Title"] = "Chi tiết Bác sĩ";
    string straddr="";
}




   

    <div class="col-xl-8 col-lg-12 col-md-12 text-center w220 mx-auto">
                        <div class="card teacher-card mb-3 flex-column">
                            <div class="card-body d-flex teacher-fulldeatil flex-column">
                                <div class="profile-teacher text-center w220 mx-auto">
                                    <a href="#">
                                        <img src="~/images/doctoravata.png" width="200" height="200" alt="" class="avatar xl rounded-circle img-thumbnail shadow-sm">
                                    </a>
                                    <div class="about-info d-flex align-items-center mt-3 justify-content-center flex-column">
                                        <span class="text-muted small">Bác Sĩ</span>
                                    </div>
                                </div>
                                <div class="teacher-info   w-100">
                                    <h6 class="mb-0 mt-2  fw-bold d-block fs-6 text-center">@Model.FullName</h6>
                                    <span class="py-1 fw-bold small-11 mb-0 mt-1 text-muted text-center mx-auto d-block">@Model.Age Tuổi , @Model.address?.City</span>
                                     @if(Model.address!=null)
                                     { straddr= @Model.address?.Street+" - "+@Model.address?.City+" - "+@Model.address.Province+" - "+@Model.address.Post_Code ;}
                                    <p class="mt-2">Địa chỉ :@straddr</p>
                                     <p class="mt-2">Phone : @Model.Phone </p>
                                     <p class="mt-2">Email : @Model.Email </p>
                                    @* <div class="row g-2 pt-2">
                                        <div class="col-xl-12">
                                            <div class="d-flex align-items-center">
                                                <i class="icofont-ui-touch-phone"></i>
                                                <span class="ms-2">@Model.Phone </span>
                                            </div>
                                        </div>
                                        <div class="col-xl-12">
                                            <div class="d-flex align-items-center">
                                                <i class="icofont-email"></i>
                                                <span class="ms-2">@Model.Email</span>
                                            </div>
                                        </div> *@
                                        @* <div class="col-xl-12">
                                            <div class="d-flex align-items-center">
                                                <i class="icofont-birthday-cake"></i>
                                                <span class="ms-2">@DateTime.Now.AddYears(Model.Age?*-1))</span>
                                            </div>
                                        </div>
                                        <div class="col-xl-12">
                                            <div class="d-flex align-items-center">
                                                <i class="icofont-address-book"></i>
                                                <span class="ms-2">2734  West Fork Street,EASTON 02334.</span>
                                            </div>
                                        </div> *@
                                    </div>
                                </div>
                            </div>
                        </div>
                        </div>
   
    
<div class="text-center">
   <div class="btn-group">
    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model.ID">Chỉnh sửa</a>
    <a class="btn btn-secondary" asp-action="index"
       asp-route-pg="@TempData["CurrentPage"]">Danh sách bác sĩ</a>    
</div>
</div>

@section Sidebar
{
    @Html.Raw(_AdminSidebarService.renderHtml())
}

Views/Doctor/Index.cshtml
@using ClinicManagement.Menu
@inject AdminSidebarService _AdminSidebarService
@model IEnumerable<ClinicManagement.Models.Doctor>

@{
    ViewData["Title"] = "Danh Sách Bác Sĩ";
    SortModel sortModel = (SortModel)ViewData["sortModel"];

    PagerModel pager = ViewBag.Pager;
}
<partial name="_StatusMessage" />

<div class="container-fluid btn-group">
<p>
    <a asp-action="Create" class="btn btn-success"><i class="fas fa-plus"></i></a>
</p>
</div>
<br/>
<div class="row">
    <div class="col-12">
        <partial name="_topBar" model="@pager" />
    </div>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                 <i class="@sortModel.GetColumn("fname").SortIcon" arial-hidden="true"></i>
                <a asp-action="Index" asp-route-sortExpression="@sortModel.GetColumn("fname").SortExpression">
                    @Html.DisplayNameFor(model => model.FName)

                </a>
            </th>
            <th>
                <i class="@sortModel.GetColumn("lname").SortIcon" arial-hidden="true"></i>
                <a asp-action="Index" asp-route-sortExpression="@sortModel.GetColumn("lname").SortExpression">
                    @Html.DisplayNameFor(model => model.LName)

                </a>
            </th>
            <th>
                 <i class="@sortModel.GetColumn("age").SortIcon" arial-hidden="true"></i>
                <a asp-action="Index" asp-route-sortExpression="@sortModel.GetColumn("age").SortExpression">
                    @Html.DisplayNameFor(model => model.Age)

                </a>
            </th>
            <th>
                 <i class="@sortModel.GetColumn("fname").SortIcon" arial-hidden="true"></i>
                <a asp-action="Index" asp-route-sortExpression="@sortModel.GetColumn("fname").SortExpression">
                    @Html.DisplayNameFor(model => model.Phone)

                </a>
            </th>
            <th>
                 <i class="@sortModel.GetColumn("fname").SortIcon" arial-hidden="true"></i>
                <a asp-action="Index" asp-route-sortExpression="@sortModel.GetColumn("fname").SortExpression">
                    @Html.DisplayNameFor(model => model.Email)

                </a>
            </th>
           
            <th>
                 <i class="@sortModel.GetColumn("fname").SortIcon" arial-hidden="true"></i>
                <a asp-action="Index" asp-route-sortExpression="@sortModel.GetColumn("fname").SortExpression">
                    @Html.DisplayNameFor(model => model.gender.Name)

                </a>
            </th>
            <th>
                 <i class="@sortModel.GetColumn("fname").SortIcon" arial-hidden="true"></i>
                <a asp-action="Index" asp-route-sortExpression="@sortModel.GetColumn("fname").SortExpression">
                    @Html.DisplayNameFor(model => model.boolGroup.Name)

                </a>
             
            </th>           
             <th>
                 <i class="@sortModel.GetColumn("fname").SortIcon" arial-hidden="true"></i>
                <a asp-action="Index" asp-route-sortExpression="@sortModel.GetColumn("fname").SortExpression">
                    @Html.DisplayNameFor(model => model.Registed_Date)
                </a>
            </th> 
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>            
            <td>
                @Html.DisplayFor(modelItem => item.gender.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.boolGroup.Name)
            </td>
           <td>
                @Html.DisplayFor(modelItem => item.Registed_Date)
            </td>
            <td>
                <div class="btn-group">
                        <a asp-action="Edit" asp-controller="Doctor" asp-route-id="@item.ID">
                            <span class="btn btn-sm btn-outline-primary">
                                <i class="fa fa-edit" aria-hidden="true"></i>
                            </span>
                        </a>

                        <a asp-action="Details" asp-route-id="@item.ID">
                            <span class="btn btn-sm btn-outline-dark">
                                <i class="fa fa-eye" aria-hidden="true"></i>
                            </span>
                        </a>

                        <a asp-action="Delete" asp-route-id="@item.ID">
                            <span class="btn btn-sm btn-outline-danger">
                                <i class="fa fa-trash" aria-hidden="true"></i>
                            </span>
                        </a>
                 </div>
            </td>
        </tr>
}
    </tbody>
</table>

<div class="row">
    <div class="col-12">
        <partial name="_bottomBar" model="@pager" />
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}
@section Sidebar
{
    @Html.Raw(_AdminSidebarService.renderHtml())
}